### ISSUE TITLE
CDN exception after installing RSL2

### ISSUE THREAD

**Issue by Moneyl** [rfg-modding/SyncFaction#7]
I downloaded and ran the SF update you posted on discord yesterday in response to category changes. I ran it on the GOG version of the game which already had an up to date copy of Terraform Patch installed. I clicked the update button and it downloaded and installed RSL2 correctly, and ran the game via the launcher.

After installing RSL2 it logged `Reading CDN for dev mods` which was followed up by these exceptions: https://gist.github.com/Moneyl/0bc13c4052c1f0c8946b055dcd652e1b
My internet was running slow at the time so I don't know if that influenced it.

**Comment by Rast1234** [comment]
`No such host is known` means that app was unable to resolve DNS name into IP address. possible reasons:

* DNS server was unavailable
* internet connection was unreliable
* target host was temporarily removed from DNS because of issues or mistakes on their end

in any way, this issue is transient and doesnt prevent you from using app, right?
